# Generated by Django 4.1.3 on 2022-11-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal', models.CharField(max_length=80)),
                ('sal1', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('agencyCompany', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip', models.IntegerField()),
                ('zip2', models.IntegerField()),
                ('url', models.URLField()),
                ('phone', models.IntegerField()),
                ('fax', models.IntegerField()),
                ('cell_phone', models.IntegerField()),
                ('email', models.EmailField(max_length=32)),
                ('skype_name', models.CharField(max_length=200)),
                ('other_contact', models.IntegerField()),
            ],
        ),
    ]
