# Generated by Django 4.1.3 on 2022-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filemaker_nyc_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaker',
            name='legislature',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assembly'), (2, 'Senate'), (3, 'Congress')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='non_nys',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VIP'), (2, 'SCIO')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='non_uai_bany',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VIP'), (2, 'Public Administration')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='other',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VIP')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='private_sector',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VIP'), (2, 'Corporate Partner')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='special_categories',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ITEG Project 2008'), (2, 'DGI Institute'), (3, 'Grand Challenges Workshop'), (4, 'Hard Copy AR'), (5, 'Personalized Letter AR')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='special_intrest',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Annual Report'), (2, 'Cooperation with China'), (3, 'Digt Society'), (4, 'ICEGOV')], null=True),
        ),
        migrations.AddField(
            model_name='filemaker',
            name='uai_bany',
            field=models.PositiveSmallIntegerField(choices=[(1, 'VIP'), (2, 'Information Faculty'), (3, 'INF Students'), (4, 'University Council'), (5, 'SUNY Brd of Trustees'), (6, 'UAIbany Foundation'), (7, 'CTG Alumni'), (8, 'CTG Staff'), (9, 'A-list'), (10, 'Public Administration'), (11, 'Fellows'), (12, 'iCEHC'), (13, 'Director')], null=True),
        ),
    ]
