# Generated by Django 4.1.3 on 2022-11-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_filemaker_legislature_filemaker_non_nys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaker',
            name='project_partners',
            field=models.PositiveSmallIntegerField(choices=[(1, 'apa'), (2, 'awt'), (3, 'beth'), (4, 'dgi'), (5, 'dg_inst'), (6, 'diggov'), (7, 'dj2'), (8, 'dmv'), (9, 'docs'), (10, 'doj'), (11, 'egov'), (12, 'eot'), (13, 'gaof'), (14, 'gateways'), (15, 'gen'), (16, 'gis'), (17, 'grpware'), (18, 'hims'), (19, 'inetsys'), (20, 'inettb'), (21, 'itgov'), (22, 'journal'), (23, 'kdi'), (24, 'kwic'), (25, 'lc'), (26, 'lg1'), (27, 'lg2'), (28, 'mfa'), (29, 'miii'), (30, 'mobile'), (31, 'nadgwg'), (32, 'newmodels'), (33, 'nysit'), (34, 'omh'), (35, 'orma'), (36, 'orps'), (37, 'proi'), (38, 'rm2020'), (39, 'tmf'), (40, 'transnational'), (41, 'uig'), (42, 'un'), (43, 'usdafs'), (44, 'utw'), (45, 'writing'), (46, 'wtc1'), (47, 'xmltb'), (48, 'open govt'), (49, 'rich context'), (50, 'vpoc'), (51, 'arra'), (52, 'ifmr'), (53, 'epa'), (54, 'ocs'), (55, 'cpath'), (56, 'smartCities'), (57, 'iChoose'), (58, 'nytd'), (59, 'BOE'), (60, 'City of Albany Code Enforcement'), (61, 'ICEGOV 2012'), (62, 'Executive Leadership'), (63, 'IT Transformation'), (64, 'World Bank'), (65, 'Open Data'), (66, 'ISCC Workshop'), (67, 'IMLS'), (68, 'Kenya-CID'), (69, 'Urban Bilight'), (70, 'Digital Towpath'), (71, 'Health Research'), (72, 'Water Quality'), (73, 'DOH Visualization'), (74, 'GAB'), (75, '25th CTG Anniv'), (76, 'DEC Water Quality'), (77, 'SCC'), (78, 'NYS ITS Data Strategy'), (79, 'AHI'), (80, 'FEMA')], null=True),
        ),
    ]
